[package]
name = "rust-one"
version = "0.1.0"
edition = "2024"

[dependencies]



pcap = "1.1.0"         # For capturing packets
etherparse = "0.13.0"  # For parsing packet contents
clap = { version = "4.5", features = ["derive"] } # For command-line args
anyhow = "1.0"         # For error handling